{{ include('prefixes.rq') }}

SELECT ?scheme ?schemeLabel ?category ?categoryLabel ?count WHERE {
    ?scheme a skos:ConceptScheme.
    VALUES (?scheme ?schemeLabel ?schemeOrder) {
        (ecodigit:area_disciplinare "Area Disciplinare" 1)
        (ecodigit:disciplina "Disciplina" 2)
        (ecodigit:settore_affine "Settore Affine" 3)
#        (ecodigit:tematica "Tematica" 4)
#        (ecodigit:tipologia "Tipologia" 5)
    }.
    {
        SELECT ?scheme (false AS ?everythingElseCategory) ?category ?categoryLabel (COUNT(1) AS ?count) WHERE {
            {{ include('simpleSearchPattern.rq') }}
            ?item dcterms:subject ?category.
            ?category
                    skos:prefLabel ?categoryLabel;
                    skos:inScheme ?scheme.
        }
        GROUP BY ?scheme ?category ?categoryLabel
    } UNION {
        SELECT ?scheme (true AS ?everythingElseCategory) (ecodigit:Uncategorized AS ?category) (COUNT(1) AS ?count) WHERE {
            {{ include('simpleSearchPattern.rq') }}
            FILTER NOT EXISTS {
                ?item dcterms:subject/skos:inScheme ?scheme.
            }.
        }
        GROUP BY ?scheme
    }
}
ORDER BY ?schemeOrder ?everythingElseCategory ?category
