{{ include('prefixes.rq') }}

#SELECT DISTINCT ?item ?title ?wktGeometry ?imageURL WHERE {
SELECT DISTINCT ?item ?title WHERE {
    {{ include('advancedSearchPattern.rq') }}
    # OPTIONAL  {
    #     ?uriOggetto locn:geometry ?geo .
    #     ?geo geo:asWKT ?wktGeometry .
    # }
    # OPTIONAL {
    #     ?uriOggetto dcterms:hasImage ?image .
    #     ?image dcterms:URL ?imageURL .
    # }
}

{% if limit %}
    LIMIT {{ limit }}
{% endif %}
