{{ include('prefixes.rq') }}

#SELECT ?item (SAMPLE(?title) AS ?title) (SAMPLE(?imageURL) AS ?imageURL) WHERE {
SELECT DISTINCT ?item ?title ?imageURL ?wktGeometry WHERE {
    {{ include('advancedSearchPattern.rq') }}
    OPTIONAL {
        ?item dcterms:hasImage ?image .
        ?image dcterms:URL ?imageURL .
    }
    OPTIONAL  {
        ?item locn:geometry ?geo .
        ?geo geo:asWKT ?wktGeometry .
    }
} #GROUP BY ?item

{% if limit %}
    LIMIT {{ limit }}
{% endif %}
