{% set typeMap = {
        "Object": "dul:Object",
        "PublicInvestmentProject": "project:PublicInvestmentProject",
        "Person": "foaf:Person",
        "Organization": "org:Organization"} %}

{{ include('simpleSearchPattern.rq') }}

{% if filters.broadTypes and filters.broadTypes|length > 1 %}
    FILTER (?broadType IN (
        {{ filters.broadTypes|map(t => typeMap[t])|join(',') }}
    )) .
{% endif %}

{% if filters.categories %}
    {% for scheme in filters.categories|keys %}
        {% set categoryGroup = filters.categories[scheme] %}
        {% if categoryGroup|length == 1 and "EmptyCategory" in categoryGroup %}
            FILTER (false).
        {% else %}
            {% set includesUncategorized = "Uncategorized" in categoryGroup %}
            {% set categoryGroup = categoryGroup|filter(v => v not in ["EmptyCategory", "Uncategorized"]) %}

            {% if categoryGroup|length > 0 and includesUncategorized %}
                {
                    {{ include('simpleSearchPattern.rq') }}
            {% endif %}

                    {% if categoryGroup|length > 0 %}
                        {% if categoryGroup|length > 1 %}
                            ?item dcterms:subject ?category_{{ loop.index }} .
                            FILTER (?category_{{ loop.index }} IN (
                                {{ categoryGroup|map(c => "ecodigit:#{c}")|join(',') }}
                            )).
                        {% else %}
                            ?item dcterms:subject ecodigit:{{ categoryGroup|first }}.
                        {% endif %}
                    {% endif %}

            {% if categoryGroup|length > 0 and includesUncategorized %}
                } UNION {
                    {{ include('simpleSearchPattern.rq') }}
            {% endif %}

                    {% if includesUncategorized %}
                        FILTER NOT EXISTS {
                            ?item dcterms:subject/skos:inScheme ecodigit:{{scheme}}.
                        }
                    {% endif %}

            {% if categoryGroup|length > 0 and includesUncategorized %}
                }
            {% endif %}

        {% endif %}
    {% endfor %}
{% endif %}

{% if filters.specificTypes and filters.specificTypes|length > 0 %}
    ?item a ?specificType .
    FILTER (?specificType IN (
        {{ filters.specificTypes|map(t => "ecodigit:#{t}")|join(',') }}
    )) .
{% endif %}
