{{ include('prefixes.rq') }}

SELECT ?item (SAMPLE(?matchingTitle) AS ?title)
        (SAMPLE(?someImageURL) AS ?imageURL)
        (SAMPLE(?someWktGeometry) AS ?wktGeometry) WHERE {
#SELECT DISTINCT ?item ?title ?imageURL ?wktGeometry WHERE {
    {{ include('advancedSearchPattern.rq') }}
    OPTIONAL {?item dcterms:hasImage/dcterms:URL ?someImageURL}.
    OPTIONAL {?item locn:geometry/geo:asWKT ?someWktGeometry}.
}
GROUP BY ?item
ORDER BY ?item

{% if limit %}
    LIMIT {{ limit }}
{% endif %}
